export const IPC_CHANNELS = {
  listProjects: "capsule:listProjects",
  createProject: "capsule:createProject",
  getProject: "capsule:getProject",
  listAgents: "capsule:listAgents",
  listSkills: "capsule:listSkills",
  listSessions: "capsule:listSessions",
  createSession: "capsule:createSession",
  renameSession: "capsule:renameSession",
  archiveSession: "capsule:archiveSession",
  deleteSession: "capsule:deleteSession",
  listMessages: "capsule:listMessages",
  sendMessage: "capsule:sendMessage",
  startRun: "capsule:startRun",
  stopRun: "capsule:stopRun",
  getRun: "capsule:getRun",
  listRuns: "capsule:listRuns",
  listRunEvents: "capsule:listRunEvents",
  verifyRun: "capsule:verifyRun",
  listArtifacts: "capsule:listArtifacts",
  listApprovals: "capsule:listApprovals",
  resolveApproval: "capsule:resolveApproval",
  readFile: "capsule:readFile",
  writeFile: "capsule:writeFile",
  listFiles: "capsule:listFiles",
  openTerminal: "capsule:openTerminal",
  getStatus: "capsule:getStatus",
  getSubsystemStatus: "capsule:getSubsystemStatus",
  connectGateway: "capsule:connectGateway",
  disconnectGateway: "capsule:disconnectGateway",
  getSettings: "capsule:getSettings",
  updateSettings: "capsule:updateSettings",
  getDiagnostics: "capsule:getDiagnostics",
  search: "capsule:search",
  listHarnesses: "capsule:listHarnesses",
  dedicateHarness: "capsule:dedicateHarness",
  spawnHarness: "capsule:spawnHarness",
} as const;

export const IPC_EVENTS = {
  state: "capsule:event:state",
  run: "capsule:event:run",
  message: "capsule:event:message",
  approval: "capsule:event:approval",
  connection: "capsule:event:connection",
} as const;
